# Generated by Django 4.0.1 on 2022-01-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tazador', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(verbose_name='date published')),
                ('tipoZona', models.CharField(max_length=200)),
                ('usoPredominante', models.CharField(max_length=200)),
                ('tipoAltura', models.IntegerField()),
            ],
        ),
    ]
