# Generated by Django 4.0.1 on 2022-01-07 20:55

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_alter_address_id_alter_country_id_alter_locality_id_and_more'),
        ('tasacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasacion',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.CharField(max_length=200)),
                ('direccion', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
            ],
        ),
        migrations.AddField(
            model_name='tasacion',
            name='propiedad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasacion.propiedad'),
        ),
    ]
